DECLARE @LIMITE_MININO INT
DECLARE @LIMITE_MAXIMO INT
DECLARE @LIMITE_BREAK INT

SET @LIMITE_MININO = 1
SET @LIMITE_MAXIMO = 10
SET @LIMITE_BREAK = 8

WHILE @LIMITE_MININO <= @LIMITE_MAXIMO
BEGIN
	PRINT @LIMITE_MININO
	SET @LIMITE_MININO = @LIMITE_MININO + 1
	IF @LIMITE_MININO = @LIMITE_BREAK
	BEGIN
		PRINT 'SAINDO POR CAUSA DO BREAK'
		BREAK
	END
END