IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL DROP TABLE TABELA_TESTE 
CREATE TABLE TABELA_TESTE (ID VARCHAR(10))

SELECT GETDATE() -- RETORNA A DATA DO COMPUTADOR
SELECT DATENAME(WEEKDAY,DATEADD(DAY, 4, GETDATE())) -- RETORNAR O DIA DA SEMANA A 4 DIAS NA FRENTE

DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT

SET @NUMERO_DIAS = 2
SELECT DATENAME(WEEKDAY,DATEADD(DAY, @NUMERO_DIAS, GETDATE()))
SET @DIA_SEMANA = DATENAME(WEEKDAY,DATEADD(DAY, @NUMERO_DIAS, GETDATE()))

IF @DIA_SEMANA = 'Domingo' or @DIA_SEMANA = 'Sábado'
	PRINT 'ESTE DIA É FIM DE SEMANA'
ELSE
	PRINT 'ESTE É UM DIA DE SEMANA'