SELECT SUM([LIMITE DE CREDITO])
FROM [TABELA DE CLIENTES]
WHERE BAIRRO = 'JARDINS'

DECLARE @LIMITE_MAXIMO FLOAT 
DECLARE @LIMITE_ATUAL FLOAT
DECLARE @BAIRRO VARCHAR(20)

SET @BAIRRO = 'JARDINS'
SET @LIMITE_MAXIMO = 500000
SELECT @LIMITE_ATUAL = SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO

IF @LIMITE_MAXIMO <= (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO )
BEGIN
	PRINT 'VALOR ESTOUROU. NÃO É POSSIVEL ABRIR NOVOS CRÉDITOS'
END
ELSE
BEGIN
	PRINT 'VALOR NÃO ESTOUROU. É POSSIVEL ABRIR NOVOS CRÉDITOS'
END


DECLARE @DATANOTA DATE
DECLARE @NUMNOTAS INT
SET @DATANOTA = '20170102'
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = @DATANOTA
IF @NUMNOTAS > 70
    PRINT 'Muita nota'
ELSE
    PRINT 'Pouca nota'
PRINT @NUMNOTAS
