DECLARE @DATA_INICIAL DATE
DECLARE @DATA_FINAL DATE

SET @DATA_INICIAL = '20170101'
SET @DATA_FINAL = '20170102'


SELECT COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA >= @DATA_INICIAL AND DATA <= @DATA_FINAL

ALTER PROCEDURE NumNotasSP @DATA_INICIAL AS DATE, @DATA_FINAL AS DATE
AS 
BEGIN
	SELECT COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA >= @DATA_INICIAL AND DATA <= @DATA_FINAL
END

EXEC NumNotasSP '20170101', '20170102'