

CREATE FUNCTION FuncTabelaNotas(@DATA_INICAL AS DATE, @DATA_FINAL AS DATE) 
RETURNS TABLE 
RETURN SELECT DISTINCT DATA, [dbo].[NumeroNota](DATA) AS NUMERO 
FROM [NOTAS FISCAIS] WHERE DATA >= @DATA_INICAL AND DATA <= @DATA_FINAL

SELECT * FROM FuncTabelaNotas('20170101','20170110')