IF OBJECT_ID('NUMERO DE NOTAS FISCAIS') IS NOT NULL
	DROP TABLE [NUMERO DE NOTAS FISCAIS]

CREATE TABLE [NUMERO DE NOTAS FISCAIS] ([DIA DA SEMANA] VARCHAR(20), [DATA] DATE, [QUANT NOTAS FISCAIS] INT)


DECLARE @DATA_INICIAL DATE
DECLARE @DATA_FINAL DATE
DECLARE @NUM_FISCAL INT
DECLARE @DIA_DA_SEMANA VARCHAR(20)

SET @DATA_INICIAL = '20170101'
SET @DATA_FINAL = '20170110'
SET @NUM_FISCAL = 0


WHILE @DATA_INICIAL <= @DATA_FINAL
BEGIN
	-- CONTAR O NUMERO DE NOTAS FISCAIS
	SELECT @NUM_FISCAL = COUNT(CPF) FROM [NOTAS FISCAIS] WHERE DATA = @DATA_INICIAL	
	--PRINT  'NA DATA: ' + CAST(@DATA_INICIAL AS VARCHAR) + ' EXITE ' + CAST(@NUM_FISCAL AS VARCHAR) + 'NOTAS FISCAIS'
	
	-- DIA DA SEMANA
	SELECT @DIA_DA_SEMANA = DATENAME(WEEKDAY, @DATA_INICIAL) 
	
	-- INCLUIR NA TABELA O DIA, A DATA E O NUMERO DE NOTAS
	INSERT INTO [NUMERO DE NOTAS FISCAIS] ([DIA DA SEMANA], [DATA], [QUANT NOTAS FISCAIS])
	VALUES (@DIA_DA_SEMANA, @DATA_INICIAL, @NUM_FISCAL)
	
	-- INCREMENTAR DATA_INICIAL
	SELECT @DATA_INICIAL = DATEADD(DAY, 1, @DATA_INICIAL)
END

SELECT * FROM [NUMERO DE NOTAS FISCAIS]



 