DECLARE @DATA_ESTABELECIDA DATE
DECLARE @QUANTIDADE_NOTAS_FISCAIS INT
SET @DATA_ESTABELECIDA = '20180328'
SELECT @QUANTIDADE_NOTAS_FISCAIS=COUNT(CPF) FROM [NOTAS FISCAIS] WHERE DATA = @DATA_ESTABELECIDA

PRINT(@QUANTIDADE_NOTAS_FISCAIS)
IF @QUANTIDADE_NOTAS_FISCAIS >= 70
	PRINT 'MUITAS NOTAS'
ELSE
	PRINT 'POUCAS NOTAS'


SELECT * FROM [NOTAS FISCAIS]


