CREATE FUNCTION EnderencoCompleto(@ENDERENCO VARCHAR(100), @CIDADE VARCHAR(50), @ESTADO VARCHAR(50), @CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN
	DECLARE @ENDERENCO_COMPLETO VARCHAR(250)
	SET @ENDERENCO_COMPLETO = @ENDERENCO + ' - ' + @CIDADE + ' - ' + @ESTADO + ' - ' + @CEP
	RETURN @ENDERENCO_COMPLETO
END

SELECT CPF, [dbo].[EnderencoCompleto]([ENDERECO 1], CIDADE, ESTADO, CEP) AS ENDERENCO_COMPLETO 
FROM [TABELA DE CLIENTES]

CREATE FUNCTION EnderencoCompleto1(@ENDERENCO VARCHAR(100), @CIDADE VARCHAR(50), @ESTADO VARCHAR(50), @CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN
	DECLARE @ENDERENCO_COMPLETO VARCHAR(250)
	SET @ENDERENCO_COMPLETO = @ENDERENCO + ' , ' + @CIDADE + ' , ' + @ESTADO + ' , ' + @CEP
	RETURN @ENDERENCO_COMPLETO
END

IF OBJECT_ID('EnderencoCompleto1', 'FN') IS NOT NULL
DROP FUNCTION EnderencoCompleto1











 