SELECT SUM(QUANTIDADE * [PREÇO])
FROM [ITENS NOTAS FISCAIS]
WHERE NUMERO = 100


-- CREATE FUNCTION FATURAMENTO_NOTA (@NUMERO AS INT) 
-- RETURNS FLOAT
-- AS
-- BEGIN
-- 	DECLARE @FATURAMENTO FLOAT	
-- 	SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS] WHERE NUMERO = @NUMERO
-- 	RETURN @FATURAMENTO
-- END


-- CREATE FUNCTION NumeroNota(@DATA AS DATE)
-- RETURNS INT
-- AS
-- 	BEGIN
-- 		DECLARE @NUM_NOTAS INT
-- 
-- 		SELECT @NUM_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATA
-- 
-- 		RETURN @NUM_NOTAS
-- 	END



SELECT dbo.NumeroNota('20170101')


