DECLARE @LIMITE_MININO INT 
DECLARE @LIMITE_MAXIMO INT
DECLARE @CONTADOR_NOTAS INT

DECLARE @TABELA_NUMERO TABLE ([NUMERO] INT, [STATUS] VARCHAR(200), [FATURAMENTO] FLOAT)

SET @LIMITE_MININO = 98
SET @LIMITE_MAXIMO = 102

SET NOCOUNT ON -- NÃO CONTAS AS LINHAS
WHILE @LIMITE_MININO <= @LIMITE_MAXIMO
BEGIN
	SELECT @CONTADOR_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE [NUMERO] = @LIMITE_MININO
	IF @CONTADOR_NOTAS > 0
		INSERT INTO @TABELA_NUMERO ([NUMERO], [STATUS], FATURAMENTO) 
		VALUES (@LIMITE_MININO, 'É NOTA FISCAL', [dbo].[FATURAMENTO_NOTA](@LIMITE_MININO))
	ELSE
		INSERT INTO @TABELA_NUMERO ([NUMERO], [STATUS], [FATURAMENTO]) VALUES (@LIMITE_MININO, 'NÃO É NOTA FISCAL', 0)
				
	SET @LIMITE_MININO = @LIMITE_MININO + 1
END



SELECT * FROM @TABELA_NUMERO