CREATE PROCEDURE BuscaPorEntidades @ENTIDADE AS VARCHAR(10)
AS
BEGIN
	IF @ENTIDADE = 'CLIENTES'
		SELECT [CPF] AS INDENTIFICADOR, [BAIRRO], [NOME] AS DESCRITOR, [BAIRRO] AS BAIRRO FROM [TABELA DE CLIENTES]	
	ELSE IF @ENTIDADE = 'VENDEDORES'
		SELECT [MATRICULA] AS INDENTIFICADOR, [BAIRRO], [NOME] AS DESCRITOR, [BAIRRO] AS BAIRRO FROM [TABELA DE VENDEDORES]
END

EXEC BuscaPorEntidades @ENTIDADE = 'CLIENTES'
EXEC BuscaPorEntidades @ENTIDADE = 'VENDEDORES'