SELECT COUNT(*)
FROM [NOTAS FISCAIS]
WHERE CPF = '19290992743' AND YEAR(DATA) = 2016

SELECT SUM(QUANTIDADE * [PREÇO])
FROM [ITENS NOTAS FISCAIS] B
	INNER JOIN [NOTAS FISCAIS] A ON A.NUMERO = B.NUMERO
WHERE CPF = '19290992743' AND YEAR([DATA]) = 2016


CREATE PROCEDURE RetornaValores @CPF AS VARCHAR(12), @ANO AS INT, @NUM_NOTAS AS INT OUTPUT, -- ESSA VARIAVEL PODE SER USADA POR QUE CHAMOU
@FATURAMENTO AS FLOAT OUTPUT
AS
BEGIN
	SELECT @NUM_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE CPF = @CPF AND YEAR(DATA) = @ANO

	SELECT SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS] B
	INNER JOIN [NOTAS FISCAIS] A ON A.NUMERO = B.NUMERO
	WHERE CPF = '19290992743' AND YEAR([DATA]) = @ANO
END

DECLARE @NUMEMRO_NOTA INT, @FATURAMENTO FLOAT
DECLARE @CPF AS VARCHAR(12), @ANO INT

SET @CPF = '19290992743'
SET @ANO = 2016

EXEC RetornaValores @CPF = @CPF, @ANO = @ANO, @NUM_NOTAS = @NUMEMRO_NOTA OUTPUT, @FATURAMENTO = @FATURAMENTO OUTPUT
SELECT @NUMEMRO_NOTA, @FATURAMENTO