DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCETUAL FLOAT, @DATA DATE, @FERIAS BIT
DECLARE @BAIRRO VARCHAR(100)

SET @MATRICULA = '00240'
SET @NOME = 'Claudia Rodrigues'
SET @PERCETUAL = 0.10
SET @DATA = '20100120'
SET @FERIAS = 1
SET @BAIRRO = 'Jardim'


INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS]  ,BAIRRO)
VALUES (@MATRICULA, @NOME, @PERCETUAL, @DATA, @FERIAS, @BAIRRO)


SELECT * FROM [TABELA DE VENDEDORES]