-- # VALE SOMENTE PARA A CONEXÃO ABERTA CORRENTE
-- ## VALE PARA TODAS AS CONEXÕES
-- @ VALE PARA QUANDO O SCRITP É EXECUTADO

CREATE TABLE #TABELA01 ([NUMEROS] INT, [STATUS] VARCHAR(200))

DECLARE @LIMITE_MININO INT 
DECLARE @LIMITE_MAXIMO INT
DECLARE @CONTADOR_NOTAS INT
DECLARE @TABELA_NUMEROS TABLE ([NUMEROS] INT, [STATUS] VARCHAR(200))

SET @LIMITE_MININO = 98
SET @LIMITE_MAXIMO = 101

SET NOCOUNT ON -- NÃO CONTAS AS LINHAS
WHILE @LIMITE_MININO <= @LIMITE_MAXIMO
BEGIN
	SELECT @CONTADOR_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE [NUMERO] = @LIMITE_MININO
	IF @CONTADOR_NOTAS > 0
		BEGIN
			INSERT INTO @TABELA_NUMEROS (NUMEROS, STATUS) VALUES (@LIMITE_MININO, 'É NOTA FISCAL')
			INSERT INTO #TABELA01 (NUMEROS, STATUS) VALUES (@LIMITE_MININO, 'É NOTA FISCAL')
		END		
	ELSE
		BEGIN
			INSERT INTO @TABELA_NUMEROS (NUMEROS, STATUS) VALUES (@LIMITE_MININO, 'NÃO É NOTA FISCAL')
			INSERT INTO #TABELA01 (NUMEROS, STATUS) VALUES (@LIMITE_MININO, 'NÃO É NOTA FISCAL')
		END				
	SET @LIMITE_MININO = @LIMITE_MININO + 1
END

SELECT * FROM @TABELA_NUMEROS
SELECT * FROM #TABELA01