IF OBJECT_ID('TABELA DE NUMEROS', 'U') IS NOT NULL
	DROP TABLE [TABELA DE NUMEROS]

CREATE TABLE [TABELA DE NUMEROS] ([NUMEROS] INT, [STATUS] VARCHAR(200))

DECLARE @LIMITE_MININO INT 
DECLARE @LIMITE_MAXIMO INT
DECLARE @CONTADOR_NOTAS INT

SET @LIMITE_MININO = 1
SET @LIMITE_MAXIMO = 100000

SET NOCOUNT ON -- NÃO CONTAS AS LINHAS
WHILE @LIMITE_MININO <= @LIMITE_MAXIMO
BEGIN
	SELECT @CONTADOR_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE [NUMERO] = @LIMITE_MININO
	IF @CONTADOR_NOTAS > 0
		INSERT INTO [TABELA DE NUMEROS] (NUMEROS, STATUS)
		VALUES (@LIMITE_MININO, 'É NOTA FISCAL')
	ELSE
		INSERT INTO [TABELA DE NUMEROS] (NUMEROS, STATUS)
		VALUES (@LIMITE_MININO, 'NÃO É NOTA FISCAL')
				
	SET @LIMITE_MININO = @LIMITE_MININO + 1
END



SELECT * FROM [TABELA DE NUMEROS]